CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_id INTEGER REFERENCES noteful_folders(id) NOT NULL,
    modified TIMESTAMPTZ NOT NULL DEFAULT now(),
    note_name TEXT NOT NULL,
    content TEXT NOT NULL
);